config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "links#index"
  resources :links, only: [:show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
    validates :title, presence: true
    validates :url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
    def index
        
    end

    def show
        @link = Link.find(params[:id])
    end

    def new
        @link = Link.new
    end

    def create
        @link = Link.create(link_params)
        if @link.save
            redirect_to @link
        else
            render :new
        end
    end

    private

    def link_params
        params.require(:link).permit(:title, :url)
    end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/application/_error_messages.html.erb
<% if target.errors.any? %>
  <div>
    <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
      <ul>
        <% target.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/index.html.erb
<%= link_to "Submit a new link", new_link_path %>

app/views/links/new.html.erb
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

<%= form_for @link do |form| %>
  <%= render "error_messages", target: @link %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <%= form.submit "Submit!" %>
<% end %>

app/views/links/show.html.erb
<%= link_to @link.title, @link.url %>